###############################################################
# Licensed to the Tianjin Langhua Ltd. under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
###############################################################
 
openapi: 3.0.0
info:
  description: 开放接口演示
  version: 1.0.0
  title: 开放接口演示
  contact:
    name: 石京海
    email: huaruhai@hotmail.com
  license:
    name: Apache License V2
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - description: Localhost Server
    url: https://localhost:8443/openapi-demo/control
tags:
  - name: 演示
    description: 开放接口演示
security:
  - oauth2Login: []
  - oauth2Bearer: []
paths:
  /testOpenApiDemoService:
    post:
      tags:
        - 演示
      summary: 获取用户角色
      description: 通过一个Groovy服务，获取用户角色
      operationId: testOpenApiDemoService
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: 要读取的用户名。如果为空，则是读取OAuth2认证对应的用户。
                  example: 'admin'
                viewIndex:
                  type: integer
                  description: 页数
                  example: "1"
                viewSize:
                  type: integer
                  description: 每页数据条数
                  example: "10"
              required:
                - viewIndex
                - viewSize
      responses:
        200:
          description: 读取用户角色列表的结果。
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/GetUserRolesSuccess'
                  - $ref: '#/components/schemas/CommonError'
              examples:
                成功时返回:
                  $ref: '#/components/examples/GetUserRolesSuccess'
                错误时返回:
                  $ref: '#/components/examples/CommonError'
        401:
          description: access token无效
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedError'
        403:
          description: 无权限。
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenError'
        405:
          description: 不支持的请求方式，只能使用post方式请求
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MethodNotAllowedError'

components:
  schemas:
    GetUserRolesSuccess:
      description: 成功返回用户角色
      type: object
      properties:
        partyId:
          type: string
          description: 用户Id
          example: '10001'
        username:
          type: string
          description: 用户名
          example: 'admin'
        status:
          description: >
            状态码
              * 200
          type: integer
          format: int32
          enum:
            - 200
        result:
          description: 这个接口的执行结果
          type: string
          example: success
        timestamp:
          description: 运行这个接口的时间戳
          type: number
          format: long
          example: 1544518149125
        roles:
          type: array
          description: 角色列表
          items:
            type: string
          example: ["总经理助理", "一号店店长"]
      required:
        - partyId
        - username
        - status
        - result

    CommonError:
      description: 返回错误信息。
      type: object
      properties:
        status:
          description: >
            状态码
              * 200
          type: integer
          format: int32
          enum:
            - 200
        result:
          description: 操作结果
          type: string
          example: 'error'
        timestamp:
          description: 时间戳
          type: number
          format: long
          example: 1544518149125
        message:
          description: 错误信息
          type: string
          example: "No message available"
        path:
          description: 出错的地址
          type: string
          example: "/openapi-demo/control/testOpenApiDemoService"
      required:
        - status
        - result

    UnauthorizedError:
      description: access_token无效。
      type: object
      properties:
        status:
          description: >
            状态码
              * 401
          type: integer
          format: int32
          enum:
            - 401
        error:
          description: >
            错误
              * Unauthorized: 未认证
          type: string
          enum:
            - Unauthorized
        timestamp:
          description: 时间戳
          type: number
          format: long
          example: 1544518149125
        message:
          description: 错误信息
          type: string
          example: "No message available"
        path:
          description: 出错的地址
          type: string
          example: "/openapi-demo/control/testOpenApiDemoService"
      required:
        - status
        - error
      example: {
                 "timestamp": 1544518149125,
                 "status": 401,
                 "error": "Unauthorized",
                 "message": "No message available",
                 "path": "/openapi-demo/control/testOpenApiDemoService"
               }

    ForbiddenError:
      description: 无权限错误信息。
      type: object
      properties:
        status:
          description: >
            状态码
              * 403
          type: integer
          enum:
            - 403
        error:
          description: >
            错误
              * Forbidden: 未认证
          type: string
          enum:
            - Forbidden
        timestamp:
          description: 时间戳
          type: number
          format: long
          example: 1544518149125
        message:
          description: 错误信息
          type: string
          example: "No message available"
        path:
          description: 出错的地址
          type: string
          example: "/openapi-demo/control/testOpenApiDemoService"
      required:
        - status
        - error
      example: {
                 "timestamp": 1544518149125,
                 "status": 403,
                 "error": "Forbidden",
                 "message": "No message available",
                 "path": "/openapi-demo/control/testOpenApiDemoService"
               }

    MethodNotAllowedError:
      description: 请求方法错误信息。
      type: object
      properties:
        status:
          description: 状态
          type: number
          format: int
          enum:
            - 405
        error:
          description: 错误
          type: string
          example: "Method Not Allowed"
        message:
          description: 错误详细信息
          type: string
          example: "Request method 'POST' not supported"
        timestamp:
          description: 时间戳
          type: number
          format: long
          example: 1544553057099
        path:
          description: 访问路径
          type: string
          example: "/oauth/v2/profile"
        exception:
          description: 异常错误源
          type: string
          example: "org.springframework.web.HttpRequestMethodNotSupportedException"
      required:
        - error
        - status
      example: {
                 "timestamp": 1544553057099,
                 "status": 405,
                 "error": "Method Not Allowed",
                 "exception": "org.springframework.web.HttpRequestMethodNotSupportedException",
                 "message": "Request method 'POST' not supported",
                 "path": "/openapi-demo/control/testOpenApiDemoService"
               }

  examples:
    GetUserRolesSuccess:
      summary: 成功获取用户角色
      value: {
               "timestamp": 1544518149125,
               "status": 200,
               "result": "success",
               "partyId": "10001",
               "username": "admin",
               "roles": ["VP", "Manager of Store No.1"]
             }

    CommonError:
      summary: 通用错误信息
      value: {
               "timestamp": 1544518149125,
               "status": 200,
               "result": "error",
               "message": "Error message",
               "path": "/openapi-demo/control/testOpenApiDemoService"
             }

    UnauthorizedError:
      summary: The access token is invalid.
      value: {
               "timestamp": 1544518149125,
               "status": 401,
               "error": "Unauthorized",
               "message": "No message available",
               "path": "/openapi-demo/control/testOpenApiDemoService"
             }

    ForbiddenError:
      summary: Error of no permission
      value: {
               "timestamp": 1544518149125,
               "status": 403,
               "error": "Forbidden",
               "message": "No message available",
               "path": "/openapi-demo/control/testOpenApiDemoService"
             }
        
    MethodNotAllowedError:
      description: Error of method not allowed
      value: {
               "timestamp": 1544553057099,
               "status": 405,
               "error": "Method Not Allowed",
               "exception": "org.springframework.web.HttpRequestMethodNotSupportedException",
               "message": "Request method 'POST' not supported",
               "path": "/openapi-demo/control/testOpenApiDemoService"
             }        

  parameters:
    access_token:
      in: query
      name: access_token
      description: access token
      required: true
      schema:
        type: string
      example: "AT-7--cEerwho2pOGI2Tw2Mm1hN838KGzvSR1"

  securitySchemes:
    oauth2Login:
      type: oauth2
      description: OAuth2登录
      flows:
        password:
          tokenUrl: '/oauth/v2/accessToken'

    oauth2Bearer:
      type: http
      description: OAuth2 access token in http bearer header
      scheme: bearer
